version: "3.3" # Versi칩n de compose

services:
  postgres: # Por convenci칩n se nombra con el mismo nombre que la imagen que usas.
    image: postgres:13 # Imagen con versi칩n
    environment: # Variables de entorno
      POSTGRES_DB: "my-ecommerce-db"
      POSTGRES_USER: "emanuel"
      POSTGRES_PASSWORD: "probando y administrando, bases vamos creando."
    ports:
      - 5432:5432 # Este puerto lo usa por defecto postgresql
    volumes: # Los volumes permiten persistir info de los contenedores.
      - ./postgres_data:/var/lib/postgresql/data
      # Por defecto, las im치genes no guardan estados, pero los volumes si.
