version: "3.3"

services:
  postgres: # Por convención se nombra con el mismo nombre que la imagen que usas.
    image: postgres:13 # Imagen con versión
    environment: # Variables de entorno
      POSTGRES_DB: "my-ecommerce-db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - 5432:5432 # Este puerto lo usa por defecto postgresql
    volumes: # Los volumes permiten persistir info de los contenedores.
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: "my-ecommerce-db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - 8080:80
